# SPDX-License-Identifier: MIT

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
dynamic = []
name = "megingjord"
version = "0.0.1"
description = ''
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Ralph Meijer", email = "ralphm@ik.nu" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "attrs",
    "streamdeck >= 0.9.5",
    "pillow >= 9.0.0",
    "pulsectl-asyncio",
    "aiohttp",
    "CairoSVG",
    "svgelements",
    "xdg_base_dirs",
    "async_lru",
]
[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-asyncio",
]
cov = [
    "megingjord[tests]",
    "coverage"
]
mypy = [
]
dev = [
    "megingjord[cov,mypy,tests]",
    "black",
    "flake8",
    "mypy",
    "pre-commit",
    "pylint",
]

[project.urls]
Documentation = "https://github.com/ralphm/megingjord#readme"
Issues = "https://github.com/ralphm/megingjord/issues"
Source = "https://github.com/ralphm/megingjord"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=megingjord --cov=tests {args}"
no-cov = "cov --no-cov {args}"

[[tool.hatch.envs.test.matrix]]
python = ["310", "311"]

[tool.mypy]
strict = true
untyped_calls_exclude="PIL"

[[tool.mypy.overrides]]
module = "StreamDeck.*,svgelements,cairosvg,pulsectl,pulsectl_asyncio"
ignore_missing_imports = true

[tool.coverage.run]
branch = true
parallel = true
omit = []

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
